name: CI

on: [push]

jobs:
  lint-node:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with: 
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Lint with eslint
        run: yarn run lint:js --no-fix --max-warnings 0
      - name: Lint with stylelint
        run: yarn run lint:css --max-warnings 0
  lint-nix:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-23.11
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint with nixpkgs-fmt
        run: nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt --check flake.nix"
  lint-rust:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust
        uses: moonrepo/setup-rust@v1
      - name: "Lint with cargo"
        run: cargo fmt --manifest-path main/Cargo.toml --all -- --check
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust
        uses: moonrepo/setup-rust@v1
      - name: Install packages
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo "http://gb.archive.ubuntu.com/ubuntu" | sudo dd of=/etc/apt/sources.list.d/jammy.list
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf libsoup2.4-dev
      - name: Run tests
        run: cargo test --manifest-path main/Cargo.toml
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust
        uses: moonrepo/setup-rust@v1
      - name: Set up Node
        uses: actions/setup-node@v4
        with: 
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Install packages
        run: |
          echo "http://gb.archive.ubuntu.com/ubuntu" | sudo dd of=/etc/apt/sources.list.d/jammy.list
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf libsoup2.4-dev
      - name: Build
        env:
          TAURI_PRIVATE_KEY: "${{ secrets.TAURI_PRIVATE_KEY }}"
          TAURI_KEY_PASSWORD: ""
          LD_LIBRARY_PATH: "/home/runner/work/erasmus/erasmus/reader/vendor/zebra/lib/x86_64:$LD_LIBRARY_PATH"
        run: yarn tauri build --verbose
